spring:
  datasource:
    username: postgres
    password: saran3112
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

